### ISSUE TITLE
Find a replacement for Gangway

### ISSUE THREAD

**Issue by ralgozino** [sighupio/fury-kubernetes-auth#11]
Gangway has been deprecated upstream. [It is no longer maintained](https://github.com/vmware-archive/gangway).

We need to find a replacement for it, or fork it and maintain it.

Could be related: #14

**Comment by nutellinoit** [comment]
We can deprecate it for now, and leave it in the module

**Comment by nutellinoit** [comment]
Maybe this can be a replacement? https://github.com/vmware-tanzu/pinniped

**Comment by ralgozino** [comment]
We've forked gangway and released gangplank that we are now using:
https://github.com/sighupio/gangplank
