### ISSUE TITLE
Update dex to the latest stable version, test it with k8s 1.25

### ISSUE THREAD

**Issue by nutellinoit** [sighupio/fury-kubernetes-auth#18]

**Comment by ralgozino** [comment]
There are no updates to Dex:
https://github.com/dexidp/dex/releases/tag/v2.35.3

Tests:
- [x] integration with LDAP + Pomerium on Kubernetes 1.25 ✅ 
- [ ] integration with Gangway + OIDC auth for kubectl (WIP)

**Comment by nutellinoit** [comment]
> There are no updates to Dex: https://github.com/dexidp/dex/releases/tag/v2.35.3
> 
> Tests:
> 
> * [x]  integration with LDAP + Pomerium on Kubernetes 1.25 ✅
> * [ ]  integration with Gangway + OIDC auth for kubectl (WIP)

Nice!

**Comment by ralgozino** [comment]
🎉
